@startuml

title Activity Diagram of the Method utils.docstring_parsers.AAParser.extractArguments()

start

:<b>DocString</b> - string, the doc-string to be parsed<

:call <b>extractLinesByTokens</b>() method with <b>DocString</b> and class attribute <b>ArgsToken</b> as arguments
-> <b>Buffer</b>::list(str)|

:remove strings from <b>Buffer</b>, which do not contain ':' character;

if (<b>Buffer</b> is empty?) then (True)
    :return empty list>
else (False)
    :initialize <b>Result</b> as an empty list;
    
    while (for each <b>String</b> in <b>Buffer</b>)
        :split <b>String</b> by ':' character;
        
        :take the first element and strip the leading and tailing
        whitespaces -> <b>Name</b> string;
        
        :take the first element and strip the leading and tailing
        whitespaces, and convert into the lower case -> <b>Rest</b> string;
        
        if (<b>Rest</b> starts with '(optional)'?) then (True)
            :add leading and tailing '/'\ncharacters to <b>Name</b> string;
        endif
        
        :add the resulting <b>Name</b> string as an element into <b>Result</b> list;
    end while
    
    :return <b>Result</b> list>
endif

stop

@enduml