!define UTILS_DOCSTRING_PARSERS_AAPARSER

!ifndef CLASSES
!include ../../Templates/Classes.cuml
!endif

class AAParser <<SINGLETON>> {
    + static_field(SkipTokens) : list(str)
    + static_field(SignatureToken) : str = 'Signature:'
    + static_field(ArgsToken) : str = 'Args:'
    __
    + static_method(extractArguments) : str -> list(str)
    __
    Recognized tokens are:
    "Args:", "Returns:", "Raises", "Attributes:",
    "Signature:", "Classes:", "Properties:", "Methods:",
    "Class methods:", "Read-only properties:", "Functions:",
    "Class attributes:", "Packages:", "Modules:", ">>>"
}