!define UTILS_DOCSTRING_PARSERS_RESTPARSER

!ifndef CLASSES
!include ../../Templates/Classes.cuml
!endif

class reSTParser <<SINGLETON>> {
    + static_field(SkipTokens) : list(str)
    + static_field(ArgsToken) : list(str) = [":param", ":parameter", ":arg",
    ":argument", ":key", ":keyword", ":type"]
    + static_field(ReturnTokens) : str = ":rtype:"
    + static_field(RaisesTokens) : list(str) = [":raises", ":raise",
    ":except", ":exception"]
    __
    + static_method(extractSignature) : str -> str OR None
    __
    Recognized tokens are:
    ":param", ":parameter", ":arg", ":argument", ":key",
    ":keyword", ":type", ":returns:", ":return:", ":rtype:",
    ":raises", ":raise", ":except", ":exception", ":var",
    ":ivar", ":cvar", ":Example:", ">>>", ".. seealso::",
    ".. warning::", ".. note::", ".. todo::",
    ".. automodule::", ":members:", ":undoc-members:",
    ":inherited-members:", ":show-inheritance:"
}