!define EXCEPTIONS_CONSTANTASSIGNMENT

!ifndef CLASSES
!include ../Templates/Classes.cuml
!endif

class ConstantAssignment {
    __
    ..special methods..
    + _ _init_ _() : str/, pos.utils.traceback.ExceptionTraceback, int/ -> None
}