!define EXCEPTIONS_NOTINDCERROR

!ifndef CLASSES
!include ../Templates/Classes.cuml
!endif

class NotInDCError {
    __
    ..special methods..
    + _ _init_ _() : str/, pos.utils.traceback.ExceptionTraceback, int/ -> None
}