@startuml

title Activity Diagram of the Special Method pos.exceptions.ErrorMixin._ _del_ _()

start

if (has attribute <b>_traceback</b>?) then (Yes)
    :delete reference stored in <b>self._traceback</b> attribute;
    
    :store None in <b>self._traceback</b> attribute;
endif

stop

@enduml