@startuml

title Activity Diagram of the Method pos.utils.logger.ConsoleLogger.enableConsoleLogging()

start

if (instance does not have the ascendant (parent) logger?) then (True)
    :add handler referenced by self.console into self._logger referenced logger;
endif

stop

@enduml