@startuml

title Activity Diagram of the Method pos.utils.logger.DualLogger.disableFileLogging()

start

if (instance attribute <b>file_logging</b> stores logging.FileHandler instance?) then (True)
    :remove handler referenced by self.file_logging from the self._logger referenced logger;
endif

stop

@enduml