!define UTILS

!ifndef COMPONENTS
!include ../Templates/Components.cuml
!endif

package(utils) {
    module(traceback) {
        class(StackTraceback)
        
        class(ExceptionTraceback)
        
        StackTraceback <|- ExceptionTraceback
    }
    
    module(docstring_parsers) {
        class(GenericParser)
        
        class(SpecificParsers)
        
        SpecificParsers -|> GenericParser
        
        function("guess_docstyle()", gds)
        
        SpecificParsers <.. gds
        
        function("indent_docstring()", ids)
        
        gds -[hidden] ids
    }
    
    traceback -[hidden]- docstring_parsers
}