!define UTILS

!ifndef COMPONENTS
!include ../Templates/Components.cuml
!endif

package(utils) {
    module(traceback) {
        class(StackTraceback)
        
        class(ExceptionTraceback)
        
        StackTraceback <|- ExceptionTraceback
    }
    
    module(dynamic_import) {
        function(import_module)
        
        function(import_from_module)
        
        import_module -[hidden] import_from_module
    }
    
    module(docstring_parsers) {
        class(GenericParser)
        
        class(SpecificParsers)
        
        GenericParser <|- SpecificParsers
        
        function("guess_docstyle()", gds)
        
        SpecificParsers <-- gds
        
        function("indent_docstring()", ids)
        
        ids -[hidden] gds
        
        GenericParser -[hidden]- ids
    }
    
    SpecificParsers -[hidden] StackTraceback
    
    gds -[hidden] import_module
    
    StackTraceback -[hidden]- import_module
    
    ExceptionTraceback -[hidden]- import_from_module
    
    docstring_parsers -[hidden] traceback
    
    module(loggers) {
        class(DualLogger)
        
        class(ConsoleLogger)
        
        DualLogger -|> ConsoleLogger
    }
    
    ids -[hidden]- DualLogger
    
    gds -[hidden]- ConsoleLogger
}