@startuml pos_utils_loggers_consolelogger_setattr

title Activity Diagram of the Method ConsoleLogger._ _setattr_ _()

start

:<b>Name</b> - string, name of the attribute to assign a value
<b>Value</b> - any type, the value to assign<
if (instance (self) has attribute '_logger'?) then (True)
    if (self._logger has attribute <b>Name</b>?) then (True)
        :assign <b>Value</b> to self._logger.Name
        using object._ _setattr_ _() method;
    else (False)
        :assign <b>Value</b> to self.Name
        using object._ _setattr_ _() method;
    endif
else (False)
    :assign <b>Value</b> to self.Name
    using object._ _setattr_ _() method;
endif

stop

@enduml
