@startuml pos_utils_docstring_parsers_numpydocparser_extractreturnedvalues

title Activity Diagram of the Method utils.docstring_parsers.NumPydocParser.extractReturnedValues()

start

:<b>DocString</b> - string, the doc-string to be parsed<

:call <b>extractLinesByTokens</b>() method with <b>DocString</b> and class attribute <b>ReturnToken</b> as arguments -> <b>Buffer</b>::list(str)|

:remove all lines (strings) from <b>Buffer</b> with the larger indentation (more spaces at the begging) than the first line|

if (<b>Buffer</b> is empty?) then (True)
    :return empty list>
else (False)
    :initialize <b>Result</b> as an empty list;
    
    while (for each <b>String</b> in <b>Buffer</b>)
        :split <b>String</b> by ':' character;
        
        :take the first element and strip the leading and tailing whitespaces;
        
        :add the resulting string as an element into <b>Result</b> list;
    end while
    
    :return <b>Result</b> list>
endif

stop

@enduml