@startuml

salt
{
    {T
        BaseException
        + SystemExit
        + KeyboardInterrupt
        + GeneratorExit
        + Exception
        ++ StopIteration
        ++ StandardError
        +++ ArithmenticError
        ++++ OverflowError
        ++++ ZeroDivisionError
        ++++ FloatingPointError
        +++ AssertionError
        +++ AttributeError
        +++ BufferError
        +++ EnvironmentError
        ++++ IOError
        ++++ OSError
        +++++ WindowsError
        +++++ VMSError
        +++ EOFError
        +++ ImportError
        +++ LookupError
        ++++ KeyError
        ++++ IndexError
        +++ MemoryError
        +++ NameError
        ++++ UnboundLocalError
        +++ ReferenceError
        +++ RuntimeError
        ++++ NotImplementedError
        +++ SyntaxError
        ++++ IndentationError
        +++++ TabError
        +++ SystemError
        +++ TypeError
        +++ ValueError
        ++++ UnicodeError
        +++++ UnicodeDecodeError
        +++++ UnicodeEncodeError
        +++++ UnicodeTranslateError
        ++ Warning
        +++ DeprecationWarning
        ++++ PendingDeprecationWarning
        +++ RuntimeWarning
        +++ SyntaxWarning
        +++ UserWarning
        +++ FutureWarning
        +++ ImportWarning
        +++ UnicodeWarning
        +++ BytesWarning
    }
}

@enduml